flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps: [contravariant-1.4, StateVar-1.1.0.4, stm-2.4.4.1, mtl-2.2.1, void-0.7.1, hashable-1.2.4.0, text-1.2.2.1, parallel-3.2.1.0, vector-0.11.0.0, primitive-0.6.1.0]
resolver: lts-7.1
