flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps: [QuickCheck-2.8.2, random-1.1, tf-random-0.5, primitive-0.6.1.0, bifunctors-5.4.1, comonad-5, contravariant-1.4, void-0.7.1, hashable-1.2.4.0, text-1.2.2.1, StateVar-1.1.0.4, stm-2.4.4.1, mtl-2.2.1, parallel-3.2.1.0]
resolver: lts-7.3
